---

services:
  stack-java-httpd:
    container_name: stack-java-httpd
    image: stack-java-httpd:1.0
    ## politique de build dans docker compose
    # 1. si l'image en local pas de build
    # 2. sinon build
    # 3. sans le cache no_cache (ou docker buildx prune)
    # REM: pas de build avec docker compose sur SWARM cluster
    build:
      context: ./httpd
      dockerfile: Dockerfile
      # no_cache: true
    restart: unless-stopped
    ports:
      - 8081:80
    networks:
      - stack_java
    depends_on:
      - stack-java-tomcat
    labels:
      - truc.machin=bidule
    # on désactive la capacité "chown" du root du conteneur 
    cap_drop:
      - CAP_CHOWN
    # CGROUPS limite max phys. de ram allouable dans le conteneur
    mem_limit: 300m

  stack-java-tomcat:
    container_name: stack-java-tomcat
    image: stack-java-tomcat:1.0
    build:
      context: ./tomcat
      dockerfile: Dockerfile
      args:
        - TOMCAT_VERSION_MAJOR=${TOMCAT_VERSION_MAJOR:-9}
        - TOMCAT_VERSION_FULL=${TOMCAT_VERSION_FULL:-9.0.93}
    restart: unless-stopped
    networks:
      - stack_java
    # healthcheck:
    #   test: ["executable", "arg"]
    #   interval: 1m30s
    #   timeout: 30s
    #   retries: 5
    #   start_period: 30s

networks:
  # arbitraire (par défaut ce nom est préfixé par le dossier parent)
  stack_java:
    # fixer le nom
    name: stack_java
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.1