## on commence toujours avec une image de base
#  FROM scratch => pour les images de distrutions (ubuntu /debian / alpine ...)
FROM httpd:2.4


## métadonnée => documentation et filtrage
LABEL author="matt"
LABEL created_at="2024-10-29"
LABEL created_at.year="2024"
LABEL stack="java"
LABEL stack.service="httpd"

