---

networks:
  # arbitraire
  stack-php:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

volumes:
  db_data:
  nfs-vol:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.30,ro
      device: :/mnt/nfs-dir

services:
  stack-php-web:
    image: nginx:1.27.1-alpine-slim
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - stack_php
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/vhost.conf:ro

  stack-php-php8.2:
    image: bitnami/php-fpm:8.2-debian-12
    restart: unless-stopped
    networks:
      - stack_php
    volumes:
      - nfs-vol:/srv
  
  stack-php-db:
    image: mariadb:11.5
    restart: unless-stopped
    networks:
      - stack_php
    env_file:
      - .env
    volumes:
      - ./mariadb-init.sql:/docker-entrypoint-initdb.d/mariadb-init.sql:ro
      - db_data:/var/lib/mysql
    

