---

services:
  # arbitraire (par défaut ce nom est préfixé par le dossier parent)
  stack-php-web:
    container_name: stack-php-web
    image: nginx:1.27.1-alpine-slim
    restart: unless-stopped
    ports:
      - 8080:80
    networks:
      - stack_php
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/vhost.conf:ro
    depends_on:
      - stack-php-php8.2

  stack-php-php8.2:
    container_name: stack-php-php8.2
    image: bitnami/php-fpm:8.2-debian-12
    restart: unless-stopped
    networks:
      - stack_php
    volumes:
      - nfs-vol:/srv
    # REM: fixer l'ordre de construction
    # REM: on spécifie le nom du service (!= nom du conteneur)
    # REM: cette préséance n'est pas une garantie (STATUS == UP)
    depends_on:
      - stack-php-db
  
  stack-php-db:
    container_name: stack-php-db
    image: mariadb:11.5
    restart: unless-stopped
    networks:
      - stack_php
    env_file:
      - .env
    volumes:
      - ./mariadb-init.sql:/docker-entrypoint-initdb.d/mariadb-init.sql:ro
      - db_data:/var/lib/mysql

  # backup:
  #   image: alpine
  #   network_mode: none
  #   volumes:
  #     - db_data:/data
  #     - ./dump:/dump
  #   # command: ["tar", "-czvf", "/dump/dump.tar.gz", "/var/lib/mysql"]
  #   command: tar -czvf /dump/dump.tar.gz /var/lib/mysql

networks:
  # arbitraire (par défaut ce nom est préfixé par le dossier parent)
  stack_php:
    # fixer le nom
    name: stack_php
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1

volumes:
  # arbitraire (par défaut ce nom est préfixé par le dossier parent)
  db_data:
    name: db_data
  nfs-vol:
    name: nfs-vol
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.30,ro
      device: :/mnt/nfs-dir